blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/stephaneglaugier91/skillet/discussions
    about: Ask questions, share ideas, or discuss usage.
